#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop observer.service || true
            systemctl disable observer.service || true
        fi
        ;;
esac

exit 0
